[package]
name = "math-algorithm-book-rust"
version = "0.1.0"
edition = "2018"
rust-version = "1.42"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
proconio = { version = "0.3.6", features = ["derive"] }